export const ACTION_GET_CREATE_LEAD_DATA= "ACTION_GET_CREATE_LEAD_DATA";
export const ACTION_CREATE_LEAD = "ACTION_CREATE_LEAD";

export const ACTION_GET_CREATE_LEAD_DATA_SUCCESS = "ACTION_GET_CREATE_LEAD_DATA_SUCCESS";
export const ACTION_GET_CREATE_LEAD_DATA_FAILED = "ACTION_GET_CREATE_LEAD_DATA_FAILED";

export const ACTION_CREATE_LEAD_SUBMIT_SUCCESS = "ACTION_CREATE_LEAD_SUBMIT_SUCCESS";
export const ACTION_CREATE_LEAD_SUBMIT_FAILED = "ACTION_CREATE_LEAD_SUBMIT_FAILED";