export const GET_UNIT_PLANS_REQUEST = 'GET_UNIT_PLANS_REQUEST';
export const GET_UNIT_PLANS_SUCCESS = 'GET_UNIT_PLANS_SUCCESS';
export const GET_UNIT_PLANS_FAILURE = 'GET_UNIT_PLANS_FAILURE';

export const DELETE_UNIT_PLAN_REQUEST = 'DELETE_UNIT_PLAN_REQUEST';
export const DELETE_UNIT_PLAN_SUCCESS = 'DELETE_UNIT_PLAN_SUCCESS';
export const DELETE_UNIT_PLAN_FAILURE = "DELECT_UNIT_PLAN_FAILURE";

